### ISSUE TITLE
Android Gradle issue 

### ISSUE THREAD

**Issue by ShimaaSamir54** [botter-live/botter.live-Android#1]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.bluecrunch:botter:1.5.0.
     Required by:
         project :app
      > Skipped due to earlier error

**Comment by botter-live** [comment]
Hello @ShimaaSamir54, 
Our SDK is paid, you need to **[contact our support](https://botter.ai/contact/)** to get your username and password and start enjoying the experience.

After that, you should add the below lines under **all projects -> repositories** in **build.gradle (project level)**.

```
maven {
  url "from our support team"
     credentials {
       username = "*ask for your username*" //from our support team
       password = "*ask for your password*" //from our support team
    }
}
```

For more please check the **[installation guide](https://github.com/botter-live/botter.live-Android#Installation)** in the docs.

**Comment by ShimaaSamir54** [comment]
Hi 
Thanks for replying 
I know that 
I already get url , username and password and put them  but It gives me the same issue when I re-build the project

**Comment by botter-live** [comment]
Can you please send your credentials on **karim.abdelhameed@bluecrunch.com** ?, and we will follow-up with you via mail.

**Comment by ShimaaSamir54** [comment]
I send u email with my credentials
Thanks

**Comment by ShimaaSamir54** [comment]
It works now thanks
